apiVersion: v1
kind: Secret
metadata:
  name: {{ include "pumperly.secretName" . }}
  labels:
    {{- include "pumperly.labels" . | nindent 4 }}
type: Opaque
stringData:
  DATABASE_URL: {{ include "pumperly.databaseUrl" . | quote }}
  POSTGRES_USER: {{ .Values.postgis.auth.username | quote }}
  POSTGRES_PASSWORD: {{ .Values.postgis.auth.password | quote }}
  POSTGRES_DB: {{ .Values.postgis.auth.database | quote }}
  {{- if .Values.apiKeys.tankerkoenig }}
  PUMPERLY_TANKERKOENIG_API_KEY: {{ .Values.apiKeys.tankerkoenig | quote }}
  {{- end }}
  {{- if .Values.apiKeys.openChargeMap }}
  PUMPERLY_OPEN_CHARGE_MAP_API_KEY: {{ .Values.apiKeys.openChargeMap | quote }}
  {{- end }}
  {{- if .Values.apiKeys.fuelpricesDk }}
  PUMPERLY_FUELPRICES_DK_API_KEY: {{ .Values.apiKeys.fuelpricesDk | quote }}
  {{- end }}
  {{- if .Values.apiKeys.maxmind }}
  PUMPERLY_MAXMIND_LICENSE_KEY: {{ .Values.apiKeys.maxmind | quote }}
  {{- end }}
